package asu.bank.hibernateFiles;

// Generated Oct 24, 2014 12:58:34 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Login generated by hbm2java
 */
@Entity
@Table(name = "login", catalog = "surakshit_bank")
public class Login implements java.io.Serializable {

	private String sessionId;
	//private User user;
	private Date sessionCreatedAt;

	public Login() {
	}

	public Login(String sessionId, User user, Date sessionCreatedAt) {
		this.sessionId = sessionId;
		//this.user = user;
		this.sessionCreatedAt = sessionCreatedAt;
	}

	@Id
	@Column(name = "SessionID", unique = true, nullable = false, length = 40)
	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	/*@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}
*/
	@Column(name = "SessionCreatedAt", nullable = false, length = 0)
	public Date getSessionCreatedAt() {
		return this.sessionCreatedAt;
	}

	public void setSessionCreatedAt(Date sessionCreatedAt) {
		this.sessionCreatedAt = sessionCreatedAt;
	}

}
