package asu.bank.hibernateFiles;

// Generated Oct 24, 2014 12:58:34 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Operationstatus generated by hbm2java
 */
@Entity
@Table(name = "operationstatus", catalog = "surakshit_bank")
public class Operationstatus implements java.io.Serializable {

	private OperationstatusId id;
	private Operation operation;
	private Date operationStatusCreatedAt;

	public Operationstatus() {
	}

	public Operationstatus(OperationstatusId id, Operation operation,
			Date operationStatusCreatedAt) {
		this.id = id;
		this.operation = operation;
		this.operationStatusCreatedAt = operationStatusCreatedAt;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "operationId", column = @Column(name = "OperationID", nullable = false)),
			@AttributeOverride(name = "operationStatus", column = @Column(name = "OperationStatus", nullable = false, length = 20)) })
	public OperationstatusId getId() {
		return this.id;
	}

	public void setId(OperationstatusId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OperationID", nullable = false, insertable = false, updatable = false)
	public Operation getOperation() {
		return this.operation;
	}

	public void setOperation(Operation operation) {
		this.operation = operation;
	}

	@Column(name = "OperationStatusCreatedAt", nullable = false, length = 0)
	public Date getOperationStatusCreatedAt() {
		return this.operationStatusCreatedAt;
	}

	public void setOperationStatusCreatedAt(Date operationStatusCreatedAt) {
		this.operationStatusCreatedAt = operationStatusCreatedAt;
	}

}
