package asu.bank.hibernateFiles;

// Generated Oct 24, 2014 12:58:34 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OperationstatusId generated by hbm2java
 */
@Embeddable
public class OperationstatusId implements java.io.Serializable {

	private Integer operationId;
	private String operationStatus;

	public OperationstatusId() {
	}

	public OperationstatusId(Integer operationId, String operationStatus) {
		this.operationId = operationId;
		this.operationStatus = operationStatus;
	}

	@Column(name = "OperationID", nullable = false)
	public Integer getOperationId() {
		return this.operationId;
	}

	public void setOperationId(Integer operationId) {
		this.operationId = operationId;
	}

	@Column(name = "OperationStatus", nullable = false, length = 20)
	public String getOperationStatus() {
		return this.operationStatus;
	}

	public void setOperationStatus(String operationStatus) {
		this.operationStatus = operationStatus;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OperationstatusId))
			return false;
		OperationstatusId castOther = (OperationstatusId) other;

		return ((this.getOperationId() == castOther.getOperationId()) || (this
				.getOperationId() != null && castOther.getOperationId() != null && this
				.getOperationId().equals(castOther.getOperationId())))
				&& ((this.getOperationStatus() == castOther
						.getOperationStatus()) || (this.getOperationStatus() != null
						&& castOther.getOperationStatus() != null && this
						.getOperationStatus().equals(
								castOther.getOperationStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getOperationId() == null ? 0 : this.getOperationId()
						.hashCode());
		result = 37
				* result
				+ (getOperationStatus() == null ? 0 : this.getOperationStatus()
						.hashCode());
		return result;
	}

}
