package asu.bank.hibernateFiles;

// Generated Oct 24, 2014 12:58:34 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Operation generated by hbm2java
 */
@Entity
@Table(name = "operation", catalog = "surakshit_bank")
public class Operation implements java.io.Serializable {

	private Integer operationId;
	private User user;
	private String operationType;
	private String operationCurrentStatus;
	private Set<Operationstatus> operationstatuses = new HashSet(0);

	public Operation() {
	}

	public Operation(User user, String operationType,
			String operationCurrentStatus) {
		this.user = user;
		this.operationType = operationType;
		this.operationCurrentStatus = operationCurrentStatus;
	}

	public Operation(User user, String operationType,
			String operationCurrentStatus, Set operationstatuses) {
		this.user = user;
		this.operationType = operationType;
		this.operationCurrentStatus = operationCurrentStatus;
		this.operationstatuses = operationstatuses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "OperationID", unique = true, nullable = false)
	public Integer getOperationId() {
		return this.operationId;
	}

	public void setOperationId(Integer operationId) {
		this.operationId = operationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "OperationType", nullable = false, length = 20)
	public String getOperationType() {
		return this.operationType;
	}

	public void setOperationType(String operationType) {
		this.operationType = operationType;
	}

	@Column(name = "OperationCurrentStatus", nullable = false, length = 20)
	public String getOperationCurrentStatus() {
		return this.operationCurrentStatus;
	}

	public void setOperationCurrentStatus(String operationCurrentStatus) {
		this.operationCurrentStatus = operationCurrentStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operation")
	public Set<Operationstatus> getOperationstatuses() {
		return this.operationstatuses;
	}

	public void setOperationstatuses(Set<Operationstatus> operationstatuses) {
		this.operationstatuses = operationstatuses;
	}

}
