package asu.bank.hibernateFiles;

// Generated Oct 21, 2014 2:42:50 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Room206 generated by hbm2java
 */
@Entity
@Table(name = "room206", catalog = "test")
public class Room206 implements java.io.Serializable {

	private String name;
	private Integer age;
	private String sex;

	public Room206() {
	}

	public Room206(String name) {
		this.name = name;
	}

	public Room206(String name, Integer age, String sex) {
		this.name = name;
		this.age = age;
		this.sex = sex;
	}

	@Id
	@Column(name = "Name", unique = true, nullable = false, length = 25)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Age", precision = 10, scale = 0)
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "Sex", length = 6)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

}
