package asu.bank.hibernateFiles;

// Generated Oct 24, 2014 12:58:34 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TransactionsstatusId generated by hbm2java
 */
@Embeddable
public class TransactionsstatusId implements java.io.Serializable {

	private Integer transactionId;
	private String transactionStatus;

	public TransactionsstatusId() {
	}

	public TransactionsstatusId(Integer transactionId, String transactionStatus) {
		this.transactionId = transactionId;
		this.transactionStatus = transactionStatus;
	}

	@Column(name = "TransactionID", nullable = false)
	public Integer getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(Integer transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "TransactionStatus", nullable = false, length = 20)
	public String getTransactionStatus() {
		return this.transactionStatus;
	}

	public void setTransactionStatus(String transactionStatus) {
		this.transactionStatus = transactionStatus;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TransactionsstatusId))
			return false;
		TransactionsstatusId castOther = (TransactionsstatusId) other;

		return ((this.getTransactionId() == castOther.getTransactionId()) || (this
				.getTransactionId() != null
				&& castOther.getTransactionId() != null && this
				.getTransactionId().equals(castOther.getTransactionId())))
				&& ((this.getTransactionStatus() == castOther
						.getTransactionStatus()) || (this
						.getTransactionStatus() != null
						&& castOther.getTransactionStatus() != null && this
						.getTransactionStatus().equals(
								castOther.getTransactionStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getTransactionId() == null ? 0 : this.getTransactionId()
						.hashCode());
		result = 37
				* result
				+ (getTransactionStatus() == null ? 0 : this
						.getTransactionStatus().hashCode());
		return result;
	}

}
