package asu.bank.hibernateFiles;

// Generated Oct 24, 2014 12:58:34 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Transactionsstatus generated by hbm2java
 */
@Entity
@Table(name = "transactionsstatus", catalog = "surakshit_bank")
public class Transactionsstatus implements java.io.Serializable {

	private TransactionsstatusId id;
	private Transaction transaction;
	private Date transactionStatusCreatedAt;

	public Transactionsstatus() {
	}

	public Transactionsstatus(TransactionsstatusId id, Transaction transaction,
			Date transactionStatusCreatedAt) {
		this.id = id;
		this.transaction = transaction;
		this.transactionStatusCreatedAt = transactionStatusCreatedAt;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "transactionId", column = @Column(name = "TransactionID", nullable = false)),
			@AttributeOverride(name = "transactionStatus", column = @Column(name = "TransactionStatus", nullable = false, length = 20)) })
	public TransactionsstatusId getId() {
		return this.id;
	}

	public void setId(TransactionsstatusId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TransactionID", nullable = false, insertable = false, updatable = false)
	public Transaction getTransaction() {
		return this.transaction;
	}

	public void setTransaction(Transaction transaction) {
		this.transaction = transaction;
	}

	@Column(name = "TransactionStatusCreatedAt", nullable = false, length = 0)
	public Date getTransactionStatusCreatedAt() {
		return this.transactionStatusCreatedAt;
	}

	public void setTransactionStatusCreatedAt(Date transactionStatusCreatedAt) {
		this.transactionStatusCreatedAt = transactionStatusCreatedAt;
	}

}
